name: App With Github Actions with CD
on:
  workflow_dispatch
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: madsensss/app-with-argocd-basic
        ref: main
        token: ${{ secrets.TOKEN }}

    - name: Set up Image
      run: |
        sed -i "s%image: nginx:1.25%image: nginx:latest%" ./argocd-deployment.yaml

    - name: Commit and push changes
      run: |
        git config --local user.email "madsenss@naver.com"
        git config --local user.name "madsensss"
        git add .
        git commit -m "Update nginx image to latest"
        git push