apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: k8s12345
            - name: MYSQL_DATABASE
              value: app
            - name: MYSQL_USER
              value: app
            - name: MYSQL_PASSWORD
              value: app12345
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldata
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-init-sql
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: db-pvc
        - name: mysql-init-sql
          configMap:
            name: mysql-init-sql