apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-container
          image: madsens/app-with-argocd:80b629567243af5f87cc577878fc0161b1e84a15
          ports:
            - containerPort: 8080