name: App with Github Actions, ArgoCD, EKS, ECR

on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Make application.properties
      run: |
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties
      shell: bash

    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml
      
    - name: Naming jar file
      run: mv ./target/*.jar ./target/app.jar

    - name: Check jar file
      run: ls ./target

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Login to Amazon ECR Private
      id: login-ecr-private
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private

    - name: Build, tag, and push docker image to Amazon ECR Private
      env:
        REGISTRY: ${{ secrets.ECR_PRIVATE_ID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com
        REPOSITORY: ${{ secrets.ECR_PRIVATE_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t ${{ REGISTRY }}/${{ REPOSITORY }}:${{ IMAGE_TAG }} .
        docker push ${{ REGISTRY }}/${{ REPOSITORY }}:${{ IMAGE_TAG }}

  cd:
    runs-on: ubuntu-latest

    needs: ci
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: madsensss/eks-ecr-argocd-manifest
        ref: main
        token: ${{ secrets.TOKEN }}

    - name: Set up Image
      run: |
        sed -i "s%image: ${{ secrets.ECR_PRIVATE_ID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com/${{ secrets.ECR_PRIVATE_REPOSITORY }}:[a-zA-Z0-9._-]\+%image: ${{ secrets.ECR_PRIVATE_ID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com/${{ secrets.ECR_PRIVATE_REPOSITORY }}:${{ github.sha }}%" ./manifest/spring-deployment.yaml

    - name: Commit and push changes if needed
      run: |
        git config --local user.email "madsensss@naver.com"
        git config --local user.name "madsensss"
        
        if git diff --quiet; then
          echo "No changes to commit."
          exit 0
        fi
        
        git add ./manifest/spring-deployment.yaml
        git commit -m "Update application image version for ArgoCD"
        git push

